apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rhvi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-rhvi@sha256:f43722fb28ddd4026e8a80480667a8f6dfb5795b969b2dedff5533015749c889
        name: my-nodejs
        resources: {}
status: {}
